apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: orders-api-cpu-stress
  namespace: default
spec:
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: orders-api
  stressors:
    cpu:
      workers: 2
      load: 90
  duration: 5m
